global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 2m

scrape_configs:
  - job_name: 'node-exporter'
    scrape_interval: 10s
    scrape_timeout: 10s

    static_configs:
      - targets:
          - node_exporter:9100

remote_write:
  - url: "http://victoriametrics:8428/api/v1/write"
