services:
  website:
    image: joseluisq/static-web-server:2-alpine
    container_name: "static-web-server"
    ports:
      - 8087:80
    restart: always
    environment:
      - SERVER_ROOT=/var/public
      - SERVER_ERROR_PAGE_404=404.html
      - SERVER_ERROR_PAGE_50X=50x.html
      #- SERVER_CONFIG_FILE=/etc/config.toml
    volumes:
      - ./public:/var/public
      #- ./config.toml:/etc/config.toml
